import type {
  AcademicEntry,
  NavigationItem,
  PageRecord,
  PageSection,
  PostSummary,
  Recommendation,
  SiteSettings,
} from "@/types/content";

export const fallbackSiteSettings: SiteSettings = {
  siteName: "Tusher's Blog",
  siteTagline: "Student builder. Research-minded. AI/ML in motion.",
  siteDescription:
    "A production-grade personal knowledge platform documenting the path from CSE student to AI, ML, LLM, and MLOps professional.",
  footerBlurb:
    "A long-horizon digital identity for documenting projects, research interests, notes, and real technical growth.",
  contactEmail: "mahirfaysaltushar@gmail.com",
  locationLabel: "Dhaka, Bangladesh",
  githubUrl: "https://github.com/M-F-Tushar",
  linkedinUrl: "https://www.linkedin.com/in/mahir-faysal-tusher",
  xUrl: null,
  resumeUrl: null,
  metaTitle: "Tusher's Blog",
  metaDescription:
    "A technical identity platform for blogging, academic notes, recommendations, and learning progress in AI, ML, LLM, and MLOps.",
  canonicalUrl: null,
  ogImageUrl: null,
  defaultOgImageAssetId: null,
};

export const fallbackNavigation: NavigationItem[] = [
  {
    id: "nav-home",
    label: "Home",
    href: "/",
    location: "header",
    sortOrder: 10,
    isVisible: true,
    isExternal: false,
  },
  {
    id: "nav-about",
    label: "About",
    href: "/about",
    location: "header",
    sortOrder: 20,
    isVisible: true,
    isExternal: false,
  },
  {
    id: "nav-blogs",
    label: "Blogs",
    href: "/blogs",
    location: "header",
    sortOrder: 30,
    isVisible: true,
    isExternal: false,
  },
  {
    id: "nav-academic",
    label: "Academic",
    href: "/academic",
    location: "header",
    sortOrder: 40,
    isVisible: true,
    isExternal: false,
  },
  {
    id: "nav-recommendations",
    label: "Recommendations",
    href: "/recommendations",
    location: "header",
    sortOrder: 50,
    isVisible: true,
    isExternal: false,
  },
  {
    id: "nav-contact",
    label: "Contact",
    href: "/contact",
    location: "header",
    sortOrder: 60,
    isVisible: true,
    isExternal: false,
  },
];

export const fallbackPages: PageRecord[] = [
  {
    id: "page-home",
    pageKey: "home",
    title: "Home",
    slug: "/",
    status: "published",
    isVisible: true,
    metaTitle: "Home | Tusher's Blog",
    metaDescription: "AI/ML learning journey, technical writing, and research growth.",
    canonicalUrl: null,
  },
  {
    id: "page-about",
    pageKey: "about",
    title: "About",
    slug: "/about",
    status: "published",
    isVisible: true,
    metaTitle: "About | Tusher's Blog",
    metaDescription: "Who I am, what I study, and where I'm headed in AI/ML.",
    canonicalUrl: null,
  },
  {
    id: "page-blogs",
    pageKey: "blogs",
    title: "Blogs",
    slug: "/blogs",
    status: "published",
    isVisible: true,
    metaTitle: "Blogs | Tusher's Blog",
    metaDescription: "Learning notes, project logs, and evidence-driven technical writing.",
    canonicalUrl: null,
  },
  {
    id: "page-academic",
    pageKey: "academic",
    title: "Academic",
    slug: "/academic",
    status: "published",
    isVisible: true,
    metaTitle: "Academic | Tusher's Blog",
    metaDescription: "Coursework, experiments, research notes, and academic growth.",
    canonicalUrl: null,
  },
  {
    id: "page-recommendations",
    pageKey: "recommendations",
    title: "Recommendations",
    slug: "/recommendations",
    status: "published",
    isVisible: true,
    metaTitle: "Recommendations | Tusher's Blog",
    metaDescription: "Books, tools, courses, and resources worth recommending.",
    canonicalUrl: null,
  },
  {
    id: "page-contact",
    pageKey: "contact",
    title: "Contact",
    slug: "/contact",
    status: "published",
    isVisible: true,
    metaTitle: "Contact | Tusher's Blog",
    metaDescription: "Reach out for collaboration, conversation, or research exchange.",
    canonicalUrl: null,
  },
];

export const fallbackPageSections: PageSection[] = [
  {
    id: "home-hero",
    pageKey: "home",
    pageId: "page-home",
    sectionKey: "hero",
    sectionType: "hero",
    heading:
      "I'm a CSE student building toward AI, machine learning, LLM systems, and dependable engineering practice.",
    subheading:
      "This platform documents what I'm learning, what I'm building, and how my technical direction evolves over time.",
    bodyMarkdown:
      "I care about research depth, practical systems thinking, and honest progress. The goal is not to look finished. The goal is to become difficult to ignore through consistency and real work.",
    sortOrder: 10,
    isVisible: true,
    featured: true,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "AI engineering platform",
      focusTags: [
        "LLM systems",
        "MLOps discipline",
        "Model evaluation",
        "Research practice",
      ],
      primaryCtaLabel: "Read the journey",
      primaryCtaHref: "/blogs",
      secondaryCtaLabel: "Connect",
      secondaryCtaHref: "/contact",
      capabilitySignals: [
        {
          label: "Primary track",
          value: "AI engineering and ML systems",
        },
        {
          label: "Working style",
          value: "Research-led and documentation-first",
        },
        {
          label: "Output signal",
          value: "Visible progress over polished claims",
        },
      ],
      systemMapEyebrow: "Research system map",
      systemMapTitle: "Why this platform exists",
      systemMapBadge: "Live notebook",
      vectorLabel: "Active vectors",
      vectorBadge: "Current emphasis",
      activeVectors: [
        { label: "LLMs and orchestration", value: "82%" },
        { label: "MLOps workflow", value: "74%" },
        { label: "Applied ML", value: "68%" },
        { label: "Research literacy", value: "79%" },
      ],
    },
  },
  {
    id: "home-focus",
    pageKey: "home",
    pageId: "page-home",
    sectionKey: "current-focus",
    sectionType: "focus",
    heading: "Current focus areas",
    subheading: "The work streams shaping the next stage of growth.",
    bodyMarkdown:
      "- ML fundamentals and applied experimentation\n- LLM systems, prompting, and evaluation\n- MLOps habits: reproducibility, observability, deployment readiness\n- Technical writing and paper-reading discipline",
    sortOrder: 20,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Current vectors",
      panelTitle: "What the work is optimizing for right now",
      panelDescription:
        "A serious AI platform is part notebook, part research ledger, and part systems portfolio. These are the pillars shaping that direction.",
      columns: [
        "Learning loops that end in working systems, not just notes.",
        "Documentation that makes experiments, failures, and growth legible.",
        "A platform that proves seriousness through consistency over time.",
      ],
    },
  },
  {
    id: "home-writing",
    pageKey: "home",
    pageId: "page-home",
    sectionKey: "featured-writing",
    sectionType: "preview",
    heading: "Recent writing that reflects how the work is evolving",
    subheading:
      "A mix of learning notes, project thinking, and system-building reflections.",
    bodyMarkdown:
      "Featured posts are still selected through the content model. This section only controls the framing around them.",
    sortOrder: 30,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Featured writing",
    },
  },
  {
    id: "home-academic-preview",
    pageKey: "home",
    pageId: "page-home",
    sectionKey: "academic-preview",
    sectionType: "preview",
    heading: "Research notes, experiments, and academic continuity",
    subheading:
      "A space for paper-reading, coursework reflections, research interests, and later thesis work.",
    bodyMarkdown:
      "Featured academic entries still come from the published academic content model, while this section controls the narrative around them.",
    sortOrder: 40,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Academic and research",
    },
  },
  {
    id: "home-recommendations-preview",
    pageKey: "home",
    pageId: "page-home",
    sectionKey: "recommendations-preview",
    sectionType: "preview",
    heading: "Resources worth recommending because they genuinely help",
    subheading:
      "Tools, books, and learning assets that support real progress instead of hype.",
    bodyMarkdown:
      "Featured recommendations still come from the recommendation model and its featured flags. Admin controls this intro copy, not the underlying selection rules.",
    sortOrder: 50,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Recommendations",
    },
  },
  {
    id: "home-recent-updates",
    pageKey: "home",
    pageId: "page-home",
    sectionKey: "recent-updates",
    sectionType: "preview",
    heading: "Fresh notes and visible progress",
    subheading:
      "The platform should feel alive, not static. These entries show recent movement.",
    bodyMarkdown:
      "Recent updates remain automatically driven by published posts so the homepage stays honest and self-refreshing.",
    sortOrder: 60,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Recent updates",
    },
  },
  {
    id: "home-connect",
    pageKey: "home",
    pageId: "page-home",
    sectionKey: "connect",
    sectionType: "connect",
    heading: "If you care about AI, ML, systems, or serious learning, let us talk.",
    subheading: null,
    bodyMarkdown:
      "I am building this platform as a public record of growth. If there is a research idea, project, or conversation worth having, reach out.",
    sortOrder: 70,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Connect",
      primaryCtaLabel: "Open contact page",
      primaryCtaHref: "/contact",
      secondaryCtaLabel: "Email directly",
      tracks: [
        "Research discussion",
        "Project collaboration",
        "MLOps systems",
        "Learning network",
      ],
    },
  },
  {
    id: "about-roadmap",
    pageKey: "about",
    pageId: "page-about",
    sectionKey: "roadmap",
    sectionType: "timeline",
    heading: "Current learning roadmap",
    subheading: "Depth first, then leverage.",
    bodyMarkdown:
      "I'm building from CS fundamentals toward practical AI systems. That means strengthening statistics, ML workflows, LLM application design, and the deployment discipline needed to move from notebooks to reliable products.",
    sortOrder: 10,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {},
  },
  {
    id: "blogs-hero",
    pageKey: "blogs",
    pageId: "page-blogs",
    sectionKey: "hero",
    sectionType: "hero",
    heading: "Technical notes, project logs, paper reflections, and visible learning",
    subheading:
      "Writing is part of the work. These posts track progress, sharpen understanding, and make the journey legible.",
    bodyMarkdown:
      "The blog archive is where experiments, learning loops, and system-level thinking become public. It should read like a real engineering record, not a content calendar.",
    sortOrder: 10,
    isVisible: true,
    featured: true,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Blogs",
      panelLabel: "Writing system",
      panelItems: [
        {
          label: "Published nodes",
          value: "02",
          description: "Published posts",
        },
        {
          label: "Scope",
          value: "AI, ML, LLM, MLOps",
          description: "The themes running through the archive.",
        },
      ],
    },
  },
  {
    id: "blogs-support",
    pageKey: "blogs",
    pageId: "page-blogs",
    sectionKey: "why-writing",
    sectionType: "detail",
    heading: "Why the writing matters",
    subheading: "The public notes are part of the technical system, not separate from it.",
    bodyMarkdown:
      "Writing helps convert reading, implementation, and debugging into durable understanding. It also creates an evidence trail that is useful for collaborators, hiring, and future work.",
    sortOrder: 20,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Why it matters",
    },
  },
  {
    id: "academic-hero",
    pageKey: "academic",
    pageId: "page-academic",
    sectionKey: "hero",
    sectionType: "hero",
    heading: "Coursework, research notes, experiments, and evidence of deeper study",
    subheading:
      "This section tracks academic growth, research curiosity, and the transition from student work to more serious technical exploration.",
    bodyMarkdown:
      "Academic work matters here because it creates continuity. The goal is to make paper reading, experiments, coursework, and research interests visible as a coherent trajectory.",
    sortOrder: 10,
    isVisible: true,
    featured: true,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Academic",
      panelLabel: "Research continuity",
      panelItems: [
        {
          label: "Indexed entries",
          value: "01",
          description: "Published academic records",
        },
        {
          label: "Emphasis",
          value: "Study and experiments",
          description:
            "Coursework, experiments, paper notes, and the evidence trail behind deeper study.",
        },
      ],
    },
  },
  {
    id: "academic-support",
    pageKey: "academic",
    pageId: "page-academic",
    sectionKey: "study-system",
    sectionType: "detail",
    heading: "Study is treated like an evolving research system",
    subheading: "The page is for more than grades or summaries.",
    bodyMarkdown:
      "I want this area to show how academic work compounds into engineering judgment: reading critically, documenting ideas, building experiments, and tracking the questions worth pursuing next.",
    sortOrder: 20,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Research habit",
    },
  },
  {
    id: "recommendations-hero",
    pageKey: "recommendations",
    pageId: "page-recommendations",
    sectionKey: "hero",
    sectionType: "hero",
    heading: "Resources I'd recommend because they support real progress",
    subheading:
      "Books, tools, and learning assets filtered through actual use, not generic listicle energy.",
    bodyMarkdown:
      "The goal of this page is curation, not volume. Anything listed here should be genuinely useful for building understanding, execution quality, or long-term technical taste.",
    sortOrder: 10,
    isVisible: true,
    featured: true,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Recommendations",
      panelLabel: "Curated stack",
      panelItems: [
        {
          label: "Saved resources",
          value: "01",
          description: "Published recommendations",
        },
        {
          label: "Filter",
          value: "Useful in practice",
          description:
            "Books, tools, and references that actually hold up in practice.",
        },
      ],
    },
  },
  {
    id: "recommendations-support",
    pageKey: "recommendations",
    pageId: "page-recommendations",
    sectionKey: "curation-rule",
    sectionType: "detail",
    heading: "The bar is practical usefulness, not popularity",
    subheading: "A recommendation should earn its place.",
    bodyMarkdown:
      "This page should stay selective. I only want to recommend things that improve how I learn, build, debug, or reason about systems over time.",
    sortOrder: 20,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Curation rule",
    },
  },
  {
    id: "contact-hero",
    pageKey: "contact",
    pageId: "page-contact",
    sectionKey: "hero",
    sectionType: "hero",
    heading: "Open a conversation",
    subheading:
      "If there's an idea, project, or direction worth exploring together, I'd like to hear about it.",
    bodyMarkdown:
      "The best outreach usually includes enough context to make the next step obvious: what the idea is, why it matters, and what kind of conversation would be useful.",
    sortOrder: 10,
    isVisible: true,
    featured: true,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Contact",
      tracks: [
        "Research conversations",
        "AI/ML collaboration",
        "Systems and tooling",
      ],
    },
  },
  {
    id: "contact-email",
    pageKey: "contact",
    pageId: "page-contact",
    sectionKey: "email",
    sectionType: "detail",
    heading: "mahirfaysaltushar@gmail.com",
    subheading: "Best for collaboration, research questions, or project discussion.",
    bodyMarkdown: "",
    sortOrder: 20,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Email",
      href: "mailto:mahirfaysaltushar@gmail.com",
    },
  },
  {
    id: "contact-location",
    pageKey: "contact",
    pageId: "page-contact",
    sectionKey: "location",
    sectionType: "detail",
    heading: "Dhaka, Bangladesh",
    subheading:
      "Remote-friendly and open to thoughtful technical conversations across time zones.",
    bodyMarkdown: "",
    sortOrder: 30,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Location",
    },
  },
  {
    id: "contact-form",
    pageKey: "contact",
    pageId: "page-contact",
    sectionKey: "form",
    sectionType: "form",
    heading: "Start the conversation",
    subheading:
      "Use this channel for collaboration, research questions, project ideas, or thoughtful technical discussion.",
    bodyMarkdown: "A short summary, relevant links, and the kind of discussion you want make it easier to respond well.",
    sortOrder: 40,
    isVisible: true,
    featured: false,
    imageAssetId: null,
    imageUrl: null,
    settings: {
      eyebrow: "Secure intake",
      badge: "Thoughtful replies over volume",
    },
  },
];

export const fallbackPosts: PostSummary[] = [
  {
    id: "post-1",
    title: "Designing a learning system instead of chasing random tutorials",
    slug: "designing-a-learning-system",
    excerpt:
      "A note on replacing fragmented resource consumption with a structured research and build workflow.",
    bodyMarkdown:
      "I'm learning to treat technical growth as a system. That means choosing themes, keeping notes, building small proofs, and revisiting ideas until they compound.",
    status: "published",
    featured: true,
    publishedAt: "2026-03-18T08:00:00.000Z",
    coverUrl: null,
    coverAlt: null,
    categories: ["learning notes"],
    tags: ["roadmap", "systems"],
    metaTitle: null,
    metaDescription: null,
    canonicalUrl: null,
  },
  {
    id: "post-2",
    title: "What I'm looking for in an LLM project worth building",
    slug: "what-makes-an-llm-project-worth-building",
    excerpt:
      "A practical filter for choosing projects that build durable skill rather than shallow novelty.",
    bodyMarkdown:
      "I want projects that force decisions around data, retrieval quality, evaluation, and deployment tradeoffs. That's where real learning starts.",
    status: "published",
    featured: false,
    publishedAt: "2026-03-12T08:00:00.000Z",
    coverUrl: null,
    coverAlt: null,
    categories: ["llm", "project logs"],
    tags: ["evaluation"],
    metaTitle: null,
    metaDescription: null,
    canonicalUrl: null,
  },
];

export const fallbackAcademicEntries: AcademicEntry[] = [
  {
    id: "academic-1",
    title: "Paper-reading workflow for ML and LLM topics",
    slug: "paper-reading-workflow-for-ml-and-llm-topics",
    summary:
      "A lightweight process for reading papers with better retention and clearer downstream experiments.",
    bodyMarkdown:
      "I'm structuring paper reading around four passes: context, core mechanism, assumptions, and implementation ideas. The goal is to turn reading into experiments and writing.",
    entryType: "paper_note",
    status: "published",
    featured: true,
    startedAt: "2026-03-01",
    completedAt: "2026-03-02",
    externalUrl: null,
    coverUrl: null,
    coverAlt: null,
    metaTitle: null,
    metaDescription: null,
    canonicalUrl: null,
  },
];

export const fallbackRecommendations: Recommendation[] = [
  {
    id: "rec-1",
    title: "Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow",
    slug: "hands-on-machine-learning-book",
    summary:
      "A practical book for grounding intuition while still connecting ideas to real implementation.",
    bodyMarkdown:
      "I recommend this when you want a serious but approachable bridge from concepts to actual ML workflows.",
    whyRecommend:
      "It balances theory, code, and engineering sensibility better than most beginner-to-intermediate resources.",
    audience: "Students moving from fundamentals into hands-on ML practice.",
    useCase: "Building intuition while implementing end-to-end workflows.",
    level: "intermediate",
    externalUrl:
      "https://www.oreilly.com/library/view/hands-on-machine-learning/9781098125967/",
    status: "published",
    featured: true,
    category: "books",
    coverUrl: null,
    coverAlt: null,
    metaTitle: null,
    metaDescription: null,
    canonicalUrl: null,
  },
];
